### ISSUE TITLE
Use the Go toolchain's native VCS version stamping, and get rid of the Magefile build script

### ISSUE THREAD

**Issue by frou** [frou/yt2pod#42]
https://go.dev/doc/go1.18#go-version

https://magefile.org

cc @sabberworm

**Comment by sabberworm** [comment]
Now I get:


```
panic: runtime error: slice bounds out of range [:7] with length 0

goroutine 1 [running]:
main.introspectOwnVersion()
        /go/src/github.com/frou/yt2pod/setup.go:40 +0x349
main.setup()
        /go/src/github.com/frou/yt2pod/setup.go:46 +0x76
main.main()
        /go/src/github.com/frou/yt2pod/main.go:42 +0x1d
```

When running the docker image built with this change included
